#!/bin/bash
echo 'My costome linux settup'
cd
#core section could cuase conflics if moved
########################3
sudo apt-get update && sudo apt-get upgrade yadm -y
sudo apt install npm git -y
# Git
sudo apt-get install git git-core
echo "Define your Git username"
read username
git config --global user.name "$username"
echo "Define your Git email"
read email
git config --global user.email "$email"


#########################


sudo apt install openssh-server ranger password-gorilla -y
sudo apt-get install fonts-powerline
apt-get install tmux zsh
sudo apt-get install htop
TERM=xterm-256color #variable is needed for oh my tmux config
x=$(which)
chsh -s $x
sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
git clone https://github.com/bhilburn/powerlevel9k.git ~/.oh-my-zsh/custom/themes/powerlevel9k
sudo npm install -g bower
git clone https://github.com/gpakosz/.tmux.git
#the below to lines will be downloaded by yadm 
#ln -s -f .tmux/.tmux.conf
#cp .tmux/.tmux.conf.local . #

sudo apt-get install build-essential cmake python3-dev -y 
# G++
sudo apt-get install g++

sudo apt install python-setuptools -y
sudo easy_install -U pip

# Java
sudo apt-get install python-software-properties
sudo add-apt-repository ppa:webupd8team/java
sudo apt-get update
sudo apt-get install java-common oracle-java8-installer
# sudo update-alternatives --config java
sudo apt-get install oracle-java8-set-default

yadm clone https://github.com/elminino21/DotFiles_yadm


sudo apt-get install mysql-server
#Data bases
sudo ufw allow mysql

sudo apt-get install -y postgresql-9.3 postgresql-contrib-9.3 libpq-dev



echo 'vim  settup and extentions for pathogen'
sudo apt-get install vim
mkdir -p ~/.vim/autoload ~/.vim/bundle && \
curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

echo "execute pathogen#infect()" >> .vimrc
echo "syntax on" >> .vimrc
echo "filetype plugin indent on" >> .vimrc

cd ~/.vim/bundle

git clone https://github.com/jiangmiao/auto-pairs

git clone https://github.com/wolfgangmehner/c-support

git clone https://github.com/vim-scripts/c.vim

git clone https://github.com/scrooloose/nerdtree

git clone https://github.com/majutsushi/tagbar

git clone https://github.com/octol/vim-cpp-enhanced-highlight


git clone https://github.com/pangloss/vim-javascript

git clone https://github.com/myhere/vim-nodejs-complete

git clone https://github.com/juleswang/css.vim

git clone https://github.com/kien/ctrlp.vim

git clone https://github.com/othree/html5.vim

git clone https://github.com/klen/python-mode

git clone https://github.com/vim-airline/vim-airline

git clone https://github.com/airblade/vim-gitgutter

git clone https://github.com/mxw/vim-jsx

git clone https://github.com/leafgarland/typescript-vim

git clone https://github.com/sirver/ultisnips

git clone https://github.com/Valloric/YouCompleteMe.git







##############################################
cd ~/.vim/bundle/YouCompleteMe
git submodule update --init --recursive
python3 install.py --clang-completer

python3 install.py --ts-completer

